# Generated by Django 5.2.8 on 2026-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
