# Generated by Django 5.2.8 on 2025-11-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
