# Generated by Django 5.2.8 on 2026-03-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
