# Generated by Django 5.2.8 on 2026-03-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetotp_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp_code',
            field=models.CharField(max_length=255),
        ),
    ]
