# Generated by Django 5.2.8 on 2026-06-11 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_product_thumbnail_productcombo_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Product View'), ('click', 'Product Click'), ('add_to_cart', 'Add To Cart'), ('remove_from_cart', 'Remove From Cart'), ('favorite', 'Favorite'), ('search', 'Search'), ('purchase', 'Purchase')], max_length=20)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.category')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productcombo')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_2a7bc6_idx'), models.Index(fields=['user', 'event_type'], name='analytics_u_user_id_e6357f_idx'), models.Index(fields=['product'], name='analytics_u_product_c8a851_idx'), models.Index(fields=['category'], name='analytics_u_categor_827866_idx')],
            },
        ),
    ]
