# Generated by Django 5.2.8 on 2026-06-22 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode_prefix', models.CharField(blank=True, max_length=3)),
                ('lat_coarse', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('lng_coarse', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'indexes': [models.Index(fields=['state'], name='analytics_u_state_679744_idx'), models.Index(fields=['pincode_prefix'], name='analytics_u_pincode_0dec6d_idx')],
            },
        ),
    ]
