# Generated by Django 5.2.8 on 2026-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usergeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('units', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aov', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_orders', models.PositiveIntegerField(default=0)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('returning_customers', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Sales Rollup',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Product View'), ('click', 'Product Click'), ('add_to_cart', 'Add To Cart'), ('remove_from_cart', 'Remove From Cart'), ('favorite', 'Favorite'), ('search', 'Search'), ('purchase', 'Purchase'), ('page_view', 'Page View'), ('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed'), ('checkout_abandoned', 'Checkout Abandoned')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailyAnonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('metric', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add To Cart'), ('search', 'Search'), ('search_zero_result', 'Search (Zero Result)'), ('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed')], max_length=32)),
                ('dimension_key', models.CharField(blank=True, default='', max_length=64)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Anonymous Stat',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'metric'], name='analytics_d_date_5c809b_idx')],
                'unique_together': {('date', 'metric', 'dimension_key')},
            },
        ),
        migrations.CreateModel(
            name='DailyFunnelRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('event_type', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_be30c9_idx')],
                'unique_together': {('date', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='SearchTermStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('term', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('zero_result', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', '-count'],
                'indexes': [models.Index(fields=['date', '-count'], name='analytics_s_date_d28081_idx')],
                'unique_together': {('date', 'term')},
            },
        ),
    ]
