# Generated by Django 5.2.8 on 2025-11-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='context',
            new_name='content',
        ),
    ]
