# Generated by Django 5.2.8 on 2026-03-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_add_cancelled_at_and_coupon_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_usage',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum global uses', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
