# Generated by Django 5.2.8 on 2026-06-26 13:08

from django.db import migrations, models

DEFAULT_PRIVACY_CONTENT = """# Privacy Policy

Your privacy matters to us. This policy explains what we collect and why.

## Information you provide
When you create an account or place an order we collect your name, email,
phone number and shipping address so we can fulfil and support your orders.

## How we use your data
- To process orders, payments and deliveries.
- To provide account features such as order history and favorites.
- To personalise product recommendations for you when you are signed in,
  based on your browsing and purchase activity.

## Analytics
- **Signed-in activity:** for logged-in users we record product views,
  searches, cart activity and purchases to power personalised recommendations
  and to understand how our store is used.
- **Anonymous visitors:** for visitors who are not signed in we collect only
  aggregate, non-identifying statistics (such as overall page views, device
  type and approximate region derived from IP at a city/state level). We do not
  store a profile, a cookie identifier, or anything that can recognise an
  individual or a returning visitor.

## What we do not do
We do not sell your personal data. We do not use precise location, and coarse
region data for anonymous visitors is only ever stored as aggregate counts.

## Data retention
Order and account data is retained while your account is active. Aggregate
analytics are retained in summarised form and contain no personal identifiers.

## Contact
For any privacy questions or to request deletion of your account data, please
contact us through the Contact page.
"""


def seed_privacy_policy(apps, schema_editor):
    Policy = apps.get_model('admin_panel', 'Policy')
    Policy.objects.get_or_create(
        type='privacy', defaults={'content': DEFAULT_PRIVACY_CONTENT},
    )


def unseed_privacy_policy(apps, schema_editor):
    Policy = apps.get_model('admin_panel', 'Policy')
    Policy.objects.filter(type='privacy').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_coupon_max_usage_coupon_minimum_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('return', 'Return'), ('privacy', 'Privacy')], max_length=16, unique=True),
        ),
        migrations.RunPython(seed_privacy_policy, unseed_privacy_policy),
    ]
