# Generated by Django 5.2.8 on 2026-03-02 18:17

import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/', validators=[support.models.validate_chat_attachment]),
        ),
    ]
