# Generated by Django 5.2.8 on 2026-03-27 04:13

import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_chatmessage_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=support.models.get_chat_attachment_path, validators=[support.models.validate_chat_attachment]),
        ),
    ]
