# Generated by Django 5.2.8 on 2026-06-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_unique_together_review_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_gu',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_hi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_hinglish',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_mr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_pa',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_gu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_hinglish',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_mr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_pa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
