# Generated by Django 5.2.8 on 2025-12-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        ('products', '0006_productcombosearchkb_productsearchkb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productcombo'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('combo', 'Combo')], default='product', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'combo'], name='orders_orde_order_i_acc6e9_idx'),
        ),
    ]
