# Generated by Django 5.2.8 on 2026-06-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_backfill_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment'), ('razorpay', 'Razorpay')], max_length=20),
        ),
    ]
