# Generated by Django 5.2.8 on 2025-12-17 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcombo_productcomboitem_productcombo_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('section_type', models.CharField(choices=[('special', 'Our Specials'), ('new', 'Newly Launched'), ('trending', 'Trending Now'), ('bestseller', 'Best Sellers'), ('seasonal', 'Seasonal'), ('custom', 'Custom Section')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class name (e.g., fa-star)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which sections appear on homepage')),
                ('max_products', models.PositiveIntegerField(default=8, help_text='Maximum number of products to display in this section', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Section',
                'verbose_name_plural': 'Product Sections',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productcombo',
            name='badge',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle or tagline for the combo', max_length=300),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='title',
            field=models.CharField(blank=True, help_text='Custom display title for the combo (e.g., "Ultimate Spice Collection - Save 30%")', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Homepage sections where this product appears', related_name='products', to='products.productsection'),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Homepage sections where this combo appears', related_name='combos', to='products.productsection'),
        ),
    ]
