# Generated by Django 5.2.8 on 2025-12-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productsection_productcombo_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComboSearchKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyms', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('combo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_kb', to='products.productcombo')),
            ],
            options={
                'verbose_name': 'Combo Search KB',
                'verbose_name_plural': 'Combo Search KBs',
                'indexes': [models.Index(fields=['last_updated'], name='products_pr_last_up_af8a48_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSearchKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyms', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_kb', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Search KB',
                'verbose_name_plural': 'Product Search KBs',
                'indexes': [models.Index(fields=['last_updated'], name='products_pr_last_up_4cb34d_idx')],
            },
        ),
    ]
