# Generated by Django 5.2.8 on 2025-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcombosearchkb_productsearchkb'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'name'], name='products_ca_is_acti_5a5180_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'stock'], name='products_pr_is_acti_fec1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_645007_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['spice_form', 'is_active'], name='products_pr_spice_f_34d79e_idx'),
        ),
        migrations.AddIndex(
            model_name='productcombo',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_1aeba2_idx'),
        ),
        migrations.AddIndex(
            model_name='productcombo',
            index=models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_408a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='productsection',
            index=models.Index(fields=['is_active', 'display_order'], name='products_pr_is_acti_939e98_idx'),
        ),
        migrations.AddIndex(
            model_name='productsection',
            index=models.Index(fields=['section_type', 'is_active'], name='products_pr_section_b06ab0_idx'),
        ),
    ]
