# Generated by Django 5.2.8 on 2026-03-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_products_ca_slug_da4386_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., pc, box, kg', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., pc, box, kg', max_length=50, null=True),
        ),
    ]
