# Generated by Django 5.2.8 on 2026-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_unit_productcombo_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numerical value of the weight', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numerical value of the weight', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pc', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('combo', 'Combo')], help_text='e.g., pc, box, kg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productcombo',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pc', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('combo', 'Combo')], help_text='e.g., pc, box, kg', max_length=50, null=True),
        ),
    ]
