# Generated by Django 5.2.8 on 2026-03-02 15:50

import re
from django.db import migrations

def split_weight(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.weight:
            weight_str = product.weight.lower().strip()
            match = re.match(r'^([\d.]+)\s*([a-z]+)$', weight_str)
            if match:
                product.weight_value = match.group(1)
                unit_str = match.group(2)
                if unit_str in ['g', 'grams', 'gram']:
                    product.unit = 'g'
                elif unit_str in ['kg', 'kgs', 'kilograms', 'kilogram']:
                    product.unit = 'kg'
                elif unit_str in ['ml', 'milliliters']:
                    product.unit = 'ml'
                elif unit_str in ['l', 'liters', 'liter']:
                    product.unit = 'l'
                elif unit_str in ['pc', 'pcs', 'piece', 'pieces']:
                    product.unit = 'pc'
                elif unit_str in ['box', 'boxes']:
                    product.unit = 'box'
                elif unit_str in ['pack', 'packs']:
                    product.unit = 'pack'
                else:
                    product.unit = 'g'
            else:
                try:
                    product.weight_value = float(weight_str)
                    product.unit = 'g'
                except ValueError:
                    product.weight_value = 0
                    product.unit = 'g'
            product.save()

def reverse_split(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.weight_value is not None and product.unit:
            # We construct a string like "250g" assuming integer if .00
            val = float(product.weight_value)
            if val.is_integer():
                val = int(val)
            product.weight = f"{val}{product.unit}"
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_weight_value_productcombo_weight_value_and_more'),
    ]

    operations = [
        migrations.RunPython(split_weight, reverse_split),
    ]
