# Generated by Django 5.2.8 on 2026-03-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20260302_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight_value',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='productcombo',
            old_name='weight_value',
            new_name='weight',
        ),
    ]
