# Generated by Django 5.2.8 on 2026-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_stock_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/thumbnails/'),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='combos/thumbnails/'),
        ),
    ]
