# Generated by Django 5.2.8 on 2026-06-12 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_thumbnail_productcombo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsection',
            name='max_products',
            field=models.PositiveIntegerField(default=12, help_text='Maximum number of products to display in this section', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
