# Generated by Django 5.2.8 on 2026-06-19 02:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productsectionplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Numerical value of the weight', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pc', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('combo', 'Combo')], help_text='e.g., g, kg, pc', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='The size shown by default on listings and the product page')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of this size on the product page (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['product', 'display_order', 'weight'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'), models.Index(fields=['slug'], name='products_pr_slug_d83465_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='variant_stock_non_negative'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='one_default_variant_per_product')],
            },
        ),
    ]
