# Generated by Django 5.2.8 on 2026-06-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_description_en_category_description_gu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombo',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='description_gu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='description_hinglish',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='description_mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='description_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='name_gu',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='name_hi',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='name_hinglish',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='name_mr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='name_pa',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='title_en',
            field=models.CharField(blank=True, help_text='Custom display title for the combo (e.g., "Ultimate Spice Collection - Save 30%")', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='title_gu',
            field=models.CharField(blank=True, help_text='Custom display title for the combo (e.g., "Ultimate Spice Collection - Save 30%")', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='title_hi',
            field=models.CharField(blank=True, help_text='Custom display title for the combo (e.g., "Ultimate Spice Collection - Save 30%")', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='title_hinglish',
            field=models.CharField(blank=True, help_text='Custom display title for the combo (e.g., "Ultimate Spice Collection - Save 30%")', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='title_mr',
            field=models.CharField(blank=True, help_text='Custom display title for the combo (e.g., "Ultimate Spice Collection - Save 30%")', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='title_pa',
            field=models.CharField(blank=True, help_text='Custom display title for the combo (e.g., "Ultimate Spice Collection - Save 30%")', max_length=300, null=True),
        ),
    ]
