# Generated by Django 5.2.8 on 2026-06-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_category_is_active_name_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_is_acti_4cbaf0_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_is_acti_e481bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_is_acti_040cab_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_is_acti_fdd21a_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_is_acti_45552d_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_is_acti_aab186_idx',
        ),
    ]
