# Generated by Django 5.2.8 on 2026-06-27 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_category_products_ca_is_acti_4cbaf0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='GST percentage charged on this product (e.g. 5 for 5%, 0 for exempt items like papad).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='GST percentage charged on this combo (e.g. 5 for 5%, 0 for exempt).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
